2016-10-25 16:38:42,515 - teradata.udaexec - INFO - Initializing UdaExec...
2016-10-25 16:38:42,515 - teradata.udaexec - INFO - Reading config files: ['/etc/udaexec.ini: Not Found', '/Users/vro173/udaexec.ini: Not Found', '/Users/vro173/Documents/Python_programs/udaexec.ini: Not Found']
2016-10-25 16:38:42,515 - teradata.udaexec - INFO - Found run number file: "/Users/vro173/Documents/Python_programs/.runNumber"
2016-10-25 16:38:42,515 - teradata.udaexec - INFO - Cleaning up log files older than 90 days.
2016-10-25 16:38:42,515 - teradata.udaexec - INFO - Removed 0 log files.
2016-10-25 16:38:42,542 - teradata.udaexec - INFO - Checkpoint file not found: /Users/vro173/Documents/Python_programs/HelloWorld.checkpoint
2016-10-25 16:38:42,542 - teradata.udaexec - INFO - No previous checkpoint found, executing from beginning...
2016-10-25 16:38:42,543 - teradata.udaexec - INFO - Execution Details:
/********************************************************************************
 * Application Name: HelloWorld
 *          Version: 1.0
 *       Run Number: 20161025163842-19
 *             Host: acbc32a00557
 *         Platform: Darwin-15.6.0-x86_64-i386-64bit
 *          OS User: vro173
 *   Python Version: 3.5.2
 *  Python Compiler: GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28)
 *     Python Build: ('default', 'Jul  2 2016 17:52:12')
 *  UdaExec Version: 15.10.0.20
 *     Program Name: classify_tables.py
 *      Working Dir: /Users/vro173/Documents/Python_programs
 *          Log Dir: /Users/vro173/Documents/Python_programs/logs
 *         Log File: /Users/vro173/Documents/Python_programs/logs/HelloWorld.20161025163842-19.log
 *     Config Files: ['/etc/udaexec.ini: Not Found', '/Users/vro173/udaexec.ini: Not Found', '/Users/vro173/Documents/Python_programs/udaexec.ini: Not Found']
 *      Query Bands: ApplicationName=HelloWorld;Version=1.0;JobID=20161025163842-19;ClientUser=vro173;Production=False;udaAppLogFile=/Users/vro173/Documents/Python_programs/logs/HelloWorld.20161025163842-19.log;UtilityName=PyTd;UtilityVersion=15.10.0.20
********************************************************************************/
2016-10-25 16:38:42,549 - teradata.udaexec - INFO - Creating connection: {'password': 'XXXXXX', 'method': 'odbc', 'username': 'vro173', 'system': 'oneview'}
2016-10-25 16:38:42,549 - teradata.tdodbc - INFO - Loading ODBC Library: libiodbc.dylib
2016-10-25 16:38:42,554 - teradata.tdodbc - INFO - Available drivers: Amazon Redshift, MapR Drill ODBC Driver, MySQL ODBC 5.3 ANSI Driver, MySQL ODBC 5.3 Unicode Driver, PostgreSQL Unicode, Simba SQL Server ODBC Driver, Teradata
2016-10-25 16:38:52,968 - teradata.udaexec - INFO - Connection successful. Duration: 10.419 seconds. Details: {'password': 'XXXXXX', 'method': 'odbc', 'username': 'vro173', 'system': 'oneview'}
2016-10-25 16:38:54,360 - teradata.udaexec - ERROR - Uncaught exception
Traceback (most recent call last):
  File "classify_tables.py", line 22, in <module>
    my_writer = csv.writer("out.csv", delimiter='|')
TypeError: argument 1 must have a "write" method
2016-10-25 16:38:54,367 - teradata.tdodbc - WARNING - 1 open connections found on exit, attempting to close...
2016-10-25 16:38:54,615 - teradata.udaexec - INFO - UdaExec exiting.
