2016-10-26 13:23:51,116 - teradata.udaexec - INFO - Initializing UdaExec...
2016-10-26 13:23:51,116 - teradata.udaexec - INFO - Reading config files: ['/etc/udaexec.ini: Not Found', '/Users/vro173/udaexec.ini: Not Found', '/Users/vro173/Documents/Python_programs/udaexec.ini: Not Found']
2016-10-26 13:23:51,116 - teradata.udaexec - INFO - Found run number file: "/Users/vro173/Documents/Python_programs/.runNumber"
2016-10-26 13:23:51,116 - teradata.udaexec - INFO - Cleaning up log files older than 90 days.
2016-10-26 13:23:51,116 - teradata.udaexec - INFO - Removed 0 log files.
2016-10-26 13:23:51,202 - teradata.udaexec - INFO - Checkpoint file not found: /Users/vro173/Documents/Python_programs/HelloWorld.checkpoint
2016-10-26 13:23:51,202 - teradata.udaexec - INFO - No previous checkpoint found, executing from beginning...
2016-10-26 13:23:51,202 - teradata.udaexec - INFO - Execution Details:
/********************************************************************************
 * Application Name: HelloWorld
 *          Version: 1.0
 *       Run Number: 20161026132351-28
 *             Host: acbc32a00557
 *         Platform: Darwin-15.6.0-x86_64-i386-64bit
 *          OS User: vro173
 *   Python Version: 3.5.2
 *  Python Compiler: GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28)
 *     Python Build: ('default', 'Jul  2 2016 17:52:12')
 *  UdaExec Version: 15.10.0.20
 *     Program Name: classify_tables.py
 *      Working Dir: /Users/vro173/Documents/Python_programs
 *          Log Dir: /Users/vro173/Documents/Python_programs/logs
 *         Log File: /Users/vro173/Documents/Python_programs/logs/HelloWorld.20161026132351-28.log
 *     Config Files: ['/etc/udaexec.ini: Not Found', '/Users/vro173/udaexec.ini: Not Found', '/Users/vro173/Documents/Python_programs/udaexec.ini: Not Found']
 *      Query Bands: ApplicationName=HelloWorld;Version=1.0;JobID=20161026132351-28;ClientUser=vro173;Production=False;udaAppLogFile=/Users/vro173/Documents/Python_programs/logs/HelloWorld.20161026132351-28.log;UtilityName=PyTd;UtilityVersion=15.10.0.20
********************************************************************************/
2016-10-26 13:23:51,230 - teradata.udaexec - INFO - Creating connection: {'system': 'oneview', 'method': 'odbc', 'username': 'vro173', 'password': 'XXXXXX'}
2016-10-26 13:23:51,231 - teradata.tdodbc - INFO - Loading ODBC Library: libiodbc.dylib
2016-10-26 13:23:51,241 - teradata.tdodbc - INFO - Available drivers: Amazon Redshift, MapR Drill ODBC Driver, MySQL ODBC 5.3 ANSI Driver, MySQL ODBC 5.3 Unicode Driver, PostgreSQL Unicode, Simba SQL Server ODBC Driver, Teradata
2016-10-26 13:23:58,821 - teradata.udaexec - INFO - Connection successful. Duration: 7.590 seconds. Details: {'system': 'oneview', 'method': 'odbc', 'username': 'vro173', 'password': 'XXXXXX'}
2016-10-26 13:24:11,314 - teradata.udaexec - INFO - Query Successful. Duration: 8.300 seconds, Rows: 12, Query: SELECT COLUMNNAME FROM DBC.COLUMNS where DATABASENAME='PMASTRAT_TB' AND TABLENAME = 'AND__122006';
2016-10-26 13:24:11,318 - teradata.udaexec - ERROR - Uncaught exception
Traceback (most recent call last):
  File "classify_tables.py", line 29, in <module>
    columnname = columnanme.append(x['COLUMNNAME'].strip() )
NameError: name 'columnanme' is not defined
2016-10-26 13:24:11,318 - teradata.tdodbc - WARNING - 1 open connections found on exit, attempting to close...
2016-10-26 13:24:11,637 - teradata.udaexec - INFO - UdaExec exiting.
